# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DemonstrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_demonstrationWindow(object):
    def setupUi(self, demonstrationWindow):
        demonstrationWindow.setObjectName("demonstrationWindow")
        demonstrationWindow.resize(1000, 850)
        self.centralwidget = QtWidgets.QWidget(demonstrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 480, 740))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainTextEditInfo = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEditInfo.setGeometry(QtCore.QRect(10, 10, 460, 720))
        self.plainTextEditInfo.setObjectName("plainTextEditInfo")
        self.pushButtonMenu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMenu.setGeometry(QtCore.QRect(450, 760, 90, 30))
        self.pushButtonMenu.setObjectName("pushButtonMenu")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(510, 10, 480, 360))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 460, 340))
        self.graphicsView.setObjectName("graphicsView")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(510, 390, 480, 360))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.plainTextEditScript = QtWidgets.QPlainTextEdit(self.frame_3)
        self.plainTextEditScript.setGeometry(QtCore.QRect(10, 10, 460, 340))
        self.plainTextEditScript.setObjectName("plainTextEditScript")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(340, 760, 90, 30))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(560, 760, 90, 30))
        self.pushButtonNext.setObjectName("pushButtonNext")
        demonstrationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(demonstrationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        demonstrationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(demonstrationWindow)
        self.statusbar.setObjectName("statusbar")
        demonstrationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(demonstrationWindow)
        QtCore.QMetaObject.connectSlotsByName(demonstrationWindow)

    def retranslateUi(self, demonstrationWindow):
        _translate = QtCore.QCoreApplication.translate
        demonstrationWindow.setWindowTitle(_translate("demonstrationWindow", "MainWindow"))
        self.pushButtonMenu.setText(_translate("demonstrationWindow", "MENU"))
        self.pushButtonBack.setText(_translate("demonstrationWindow", "<BACK"))
        self.pushButtonNext.setText(_translate("demonstrationWindow", "NEXT>"))
