# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frameMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(796, 593)
        self.frameMenu = QtWidgets.QFrame(Frame)
        self.frameMenu.setGeometry(QtCore.QRect(10, 10, 761, 611))
        self.frameMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMenu.setObjectName("frameMenu")
        self.treeWidgetModules = QtWidgets.QTreeWidget(self.frameMenu)
        self.treeWidgetModules.setGeometry(QtCore.QRect(20, 20, 171, 541))
        self.treeWidgetModules.setObjectName("treeWidgetModules")
        self.labelModuleName = QtWidgets.QLabel(self.frameMenu)
        self.labelModuleName.setGeometry(QtCore.QRect(220, 30, 521, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModuleName.sizePolicy().hasHeightForWidth())
        self.labelModuleName.setSizePolicy(sizePolicy)
        self.labelModuleName.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelModuleName.setFont(font)
        self.labelModuleName.setObjectName("labelModuleName")
        self.scrollArea = QtWidgets.QScrollArea(self.frameMenu)
        self.scrollArea.setGeometry(QtCore.QRect(220, 60, 521, 481))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.labelConstDescription = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelConstDescription.setGeometry(QtCore.QRect(20, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.labelConstDescription.setFont(font)
        self.labelConstDescription.setObjectName("labelConstDescription")
        self.labelModuleDescription = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelModuleDescription.setGeometry(QtCore.QRect(30, 70, 471, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModuleDescription.sizePolicy().hasHeightForWidth())
        self.labelModuleDescription.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelModuleDescription.setFont(font)
        self.labelModuleDescription.setText("")
        self.labelModuleDescription.setTextFormat(QtCore.Qt.PlainText)
        self.labelModuleDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelModuleDescription.setWordWrap(True)
        self.labelModuleDescription.setObjectName("labelModuleDescription")
        self.pushButtonStart = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonStart.setGeometry(QtCore.QRect(20, 440, 141, 23))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.groupBoxParameters = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxParameters.setGeometry(QtCore.QRect(20, 340, 471, 91))
        self.groupBoxParameters.setObjectName("groupBoxParameters")
        self.radioButtonStandard = QtWidgets.QRadioButton(self.groupBoxParameters)
        self.radioButtonStandard.setGeometry(QtCore.QRect(20, 20, 151, 17))
        self.radioButtonStandard.setObjectName("radioButtonStandard")
        self.radioButtonAttack = QtWidgets.QRadioButton(self.groupBoxParameters)
        self.radioButtonAttack.setGeometry(QtCore.QRect(20, 40, 161, 17))
        self.radioButtonAttack.setObjectName("radioButtonAttack")
        self.radioButtonAttackDefense = QtWidgets.QRadioButton(self.groupBoxParameters)
        self.radioButtonAttackDefense.setGeometry(QtCore.QRect(20, 60, 161, 17))
        self.radioButtonAttackDefense.setObjectName("radioButtonAttackDefense")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.treeWidgetModules.headerItem().setText(0, _translate("Frame", "Категории"))
        self.labelModuleName.setText(_translate("Frame", "Выберите модуль..."))
        self.labelConstDescription.setText(_translate("Frame", "Описание"))
        self.pushButtonStart.setText(_translate("Frame", "Начать демонстрацию"))
        self.groupBoxParameters.setTitle(_translate("Frame", "Параметры"))
        self.radioButtonStandard.setText(_translate("Frame", "Обычный режим"))
        self.radioButtonAttack.setText(_translate("Frame", "Атака"))
        self.radioButtonAttackDefense.setText(_translate("Frame", "Атака + защита"))
