# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frameDemonstration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(996, 714)
        self.frame_3 = QtWidgets.QFrame(Frame)
        self.frame_3.setGeometry(QtCore.QRect(520, 380, 480, 360))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.plainTextEditScript = QtWidgets.QPlainTextEdit(self.frame_3)
        self.plainTextEditScript.setGeometry(QtCore.QRect(10, 10, 460, 340))
        self.plainTextEditScript.setObjectName("plainTextEditScript")
        self.pushButtonMenu = QtWidgets.QPushButton(Frame)
        self.pushButtonMenu.setGeometry(QtCore.QRect(580, 800, 90, 30))
        self.pushButtonMenu.setObjectName("pushButtonMenu")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(10, 10, 480, 740))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainTextEditInfo = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEditInfo.setGeometry(QtCore.QRect(10, 10, 460, 720))
        self.plainTextEditInfo.setObjectName("plainTextEditInfo")
        self.pushButtonBack = QtWidgets.QPushButton(Frame)
        self.pushButtonBack.setGeometry(QtCore.QRect(470, 800, 90, 30))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonNext = QtWidgets.QPushButton(Frame)
        self.pushButtonNext.setGeometry(QtCore.QRect(690, 800, 90, 30))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.frame_2 = QtWidgets.QFrame(Frame)
        self.frame_2.setGeometry(QtCore.QRect(510, 10, 480, 360))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 460, 340))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButtonMenu.setText(_translate("Frame", "MENU"))
        self.pushButtonBack.setText(_translate("Frame", "<BACK"))
        self.pushButtonNext.setText(_translate("Frame", "NEXT>"))
